# Generated by Django 6.0.5 on 2026-06-09 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('protein_g', models.FloatField(default=0.0)),
                ('carbs_g', models.FloatField(default=0.0)),
                ('fat_g', models.FloatField(default=0.0)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
            ],
        ),
    ]
