# Generated by Django 6.0.5 on 2026-06-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_35_flash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='fiber_g',
            field=models.FloatField(default=0.0),
        ),
    ]
