# Generated by Django 6.0.5 on 2026-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini_35_flash', '0002_meallog_fiber_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='time',
            field=models.FloatField(default=0.0),
        ),
    ]
